// <auto-generated />
using System;
using BMS.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211212150135_adduserSeed")]
    partial class adduserSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BMS.Models.Entities.BookTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("BorrowedNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Revations")
                        .HasColumnType("int");

                    b.Property<int>("TotalNumber")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BookTitles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            Author = "Ddrew Neil",
                            BorrowedNumber = 0,
                            Name = "Vim实用技巧",
                            Revations = 0,
                            TotalNumber = 20
                        },
                        new
                        {
                            Id = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            Author = "Eric Evans",
                            BorrowedNumber = 0,
                            Name = "领域驱动设计",
                            Revations = 0,
                            TotalNumber = 19
                        },
                        new
                        {
                            Id = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            Author = "张嘉佳",
                            BorrowedNumber = 0,
                            Name = "云边有个小卖铺",
                            Revations = 0,
                            TotalNumber = 90
                        },
                        new
                        {
                            Id = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            Author = "吴建",
                            BorrowedNumber = 0,
                            Name = "UML基础与Rose建模案例",
                            Revations = 0,
                            TotalNumber = 30
                        });
                });

            modelBuilder.Entity("BMS.Models.Entities.BookTitleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BookTitleId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsBorrowed")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("BookTitleId");

                    b.ToTable("BookTitleItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9300e2bb-de72-42b8-a333-3d4719afb8fe"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d497461d-8063-4eab-9233-3e22af8ec771"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("3fb614cb-b664-4c2e-9d7b-25e8501b198f"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("82b35a07-3e1f-4e5b-ac06-d62d7b8df721"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f421aa0c-f57b-4171-a5e1-4f980e0c936d"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("90f0e22c-9ab7-48fe-aaa1-e3870eb8ca39"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("a38b3d9b-b6c9-4d76-8b80-2d734bca9773"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d87e5db4-f258-4fb3-b647-185c88a6fe62"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("daa76c3c-84cb-4259-bea4-852c801b1f9f"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("4d3c296a-5b4e-420e-9c08-e3296decd66a"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("3ada5d02-2612-48cf-8edc-7f4db3ac805a"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("bbccca50-fc62-4bd4-9006-64d52d356c1e"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("3e6d5a7e-97bc-406b-a83f-8e28dc0bc609"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("6ded4ae3-8b36-414f-8370-21450e6e7905"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d91dc8dd-2e33-4736-9219-f0280a003ae8"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d89ac6d1-bde3-4be5-adeb-a4c82931908b"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("046cd425-72d1-459a-b3b5-1bd2912e13b0"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f5b309be-08fb-469f-8e93-e23cba2006f2"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("5fdccd7e-4059-4455-bbcf-bf8c3b29d9af"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("78f7239f-e0f7-40f3-9331-7eff84ec1e55"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f2717147-8458-4fd9-911a-42074c1055f8"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("1b0919ec-3b24-458b-bd37-2df6cba4399d"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f20e9af1-39f3-48fb-8dfa-73769764bc65"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ecf2a47e-5868-4cff-903b-814924d0b3db"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("c75bbff4-048c-4c56-97b2-9f5f13a15c95"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9d1754fc-fd8a-4fe2-9439-1d05e27a3eb4"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("eef360d0-32db-4492-bfd8-ddb7277fe56c"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b8217fd4-e941-476d-91e2-8e00625b614f"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9694ce9b-4681-4b76-8322-57fb82105f61"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("610e864d-ab18-401d-ae7e-e0c72150c474"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("58516e0a-a7d5-4ed7-8ff2-3de09d42442e"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("7e41746c-1eed-4368-9f6f-794a4650e127"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("75110893-46f1-49e6-875b-ff41a6cafb65"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("2582af07-e384-4da4-a993-8e873b46e2fd"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("02780bc3-f94a-4e54-855c-e15f618a5037"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("bd57f19d-6ea0-4cf2-b189-374a554da0a7"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("aff32c8b-2796-4040-97a3-9c4470c1e95c"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("8f4e2495-ae7a-4d6c-827d-db6aaeffb6fc"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("eb0580c1-9892-4a2b-9910-8c5af8bc01cf"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("7408a6b3-11a6-4070-8533-173fa3949884"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("2cf8af3e-b9dd-4656-8ae8-acc8a4ef20a8"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("bebd1f56-177d-4d95-ae74-c72b8a38f3a4"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("cc156dc3-c638-4886-9f41-09b332b16db7"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("1a41fec2-f12a-4143-a010-e57f8975b695"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("854c9677-48ca-453c-ace3-cd83793e481a"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("258751ad-4abe-44eb-a538-87e3010f7c39"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("56808d21-845e-454c-b438-2dc566402665"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("232a5600-9e7a-4892-a1ad-224128625d39"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("285e09eb-5c40-44b9-9e0d-1bcb5de24e4d"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ef76072b-2772-403c-b685-46b76310c516"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("1dab887b-ffba-4b0f-bacc-4dcfd4e416b6"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("29e95eff-6b5f-4c19-b81c-f5cb26691565"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("2e0a6217-7878-4c63-8cef-83c1b8bc4b73"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("4e775b6c-f1d3-4ade-af06-18841578e4ee"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9999e404-a7c0-43eb-8124-fa4f7aa1da37"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("6be0b40c-c166-46a2-b90d-39df4ad78743"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ce29fdee-5dbb-433d-b8a9-98fa95cbd84b"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("09819962-012d-4222-90f9-c9fbc087bd43"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("12efe4aa-ca0a-4b01-8fdf-6f31ee3204b7"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("67329e24-2cfb-4440-80e8-ed8a902baddd"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("898547cc-35aa-4eb2-aa88-3717e6ffe462"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("26a6909e-4e13-4206-aa14-5357a066f81a"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("7675cdb6-30ea-4ca1-8765-53323448c84c"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("c769e604-e0ae-4042-bb01-3f561a1d3e68"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("1d0728b1-9376-4370-8862-9a818365b6fe"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("730235c7-57cc-4a1f-97b0-260e0ba909c6"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f42926a1-5c3a-46c2-b295-21b685de4358"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("921fc3dc-bd27-43da-9dcc-5b8ef15489e3"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("57b8e687-71ae-4882-87e4-2de42f272733"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9d51ad29-a892-4b5d-b0cb-ee21cf4ea397"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("8bf4a6c0-b5f9-4914-b047-24f8cfb8df62"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("8349a772-bf61-4d4b-8bc0-bc07021cd413"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("8aa5939f-932b-4555-a860-4dfcd8eebd9f"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d7f49522-2529-4e6b-aad2-0d2704b536c8"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("449097ff-822e-44a2-89df-b6e6ed27677e"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("20de28ec-bed9-4fa2-a979-725eaaef87a9"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("5cf27ef7-724a-4825-bca0-45e588f53c55"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ac121304-9c17-49ab-aceb-e7cf624c72b2"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("70e6c2ae-0cb1-4663-b920-7aa57a302ca1"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("a598aedd-8d34-4f15-b84b-4ec109b3ea83"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ca111aa7-0bb2-4585-a3f6-5b3702e9e2bc"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ba056c0f-93b5-4a14-8ba9-fc77c0c1fd6e"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("77175474-472e-427b-b86e-5a84f01b24cb"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("12e4b2c4-7712-412c-b61e-5ce72e8f7a49"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("381d3059-733c-4e66-ac88-1a1e76b7319a"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("0dd85a15-6358-4072-b853-78ca54e00308"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("bbc970eb-8c73-4234-9cb8-a28ae355d944"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b2dc1f19-0056-4eb3-a660-322f62339e14"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("2c479fdc-3e32-4253-8304-ef4bd184d16d"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("041a47f5-3653-4ecc-a0fb-e5a4cf3fcad6"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("e1b22a02-9816-4125-9939-9fef899b2350"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("854fe0cf-e0cc-417f-9dcd-038d715f7d86"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("bdca04cb-ad79-408f-99a9-f34ac5915f6e"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("609d254b-ccfc-42ab-9316-0a07fe4b4047"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("8b4cbf6e-8b28-48a9-bc14-d139486ff1ee"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("73f990a2-c621-459b-972e-df1a6dbc1a74"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("188b0d0f-0b05-460c-9b3e-b1c03652e187"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("bd2af875-aabf-4a56-8e68-462134405691"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f102223d-27ee-4665-a990-5643bf230f89"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("923f541d-72ee-4431-b900-371f17ca4a78"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("7e5574f5-542e-414b-b19d-df8d0305677a"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("8a873b29-b0c5-4f81-8074-bc4e6e8bf6a9"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("69d8e949-27f7-4a12-a500-f17c5f91a525"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("35d9d13e-4902-4e94-a6e7-293f9edb1e1e"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9ab89604-f0ee-4050-863c-d6f0e437af48"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ca666fd9-40f8-40ca-a509-b7835cba7c7f"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("39309464-45f0-45ba-8546-d3bbdd263c53"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("298f9194-bcc7-4d6f-b2df-15917db3ce49"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("c37aa2ea-68ab-47ba-986e-a3dd119b8d7d"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f9df81a2-5d60-4d30-8bad-dfc6141ef221"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("4f6f051c-f119-44cf-b86d-1f1cf96a90cd"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("04f29239-d0f1-410a-bd0c-967bdfb8fbef"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("06d90e7e-c09a-4ffa-b330-f698162696ce"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("1c31ec8b-2500-417b-97d0-09f62ebedeb8"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("094b6460-82cd-4a66-b724-86d1390edf45"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("15fade52-9783-4294-be0b-015857029278"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d73bf2a1-6886-4fb1-a594-2c2f3df7ea2e"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("60c90e27-7d36-481f-a017-f579e3a22295"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d5f117a8-5067-40a7-92f5-671e3ded031e"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("8a543e92-b9ce-436e-a488-1df60c2a3568"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("2ebc0dc8-b940-4f1a-87fc-6351c9dc7082"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("e0e74010-9f33-4206-855c-cff215366902"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("3ae27868-df0e-4e52-b293-5e72a1fa02cc"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("300d6dea-f23d-4f05-88f0-89f000f3c2ce"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("7aa5496b-09c0-453e-a46d-a6c4aa957b1f"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f25d8a78-4f6c-4c4b-8f5c-a0b568a0309d"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("2b3dd895-24bc-4d79-8739-46839765dfd9"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("a1536faf-a3cf-4cfe-821e-48a3082b1252"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("97df6f11-cded-400b-a350-e26fb87f255c"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("2aaa85db-d80e-4147-8e33-f7ae448d3c80"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("16b1a86b-1478-4487-9517-81f9fe4ac349"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d9372b35-f74c-458e-955d-94ee483c0856"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("37054619-ed9d-444c-baec-02498ae6c767"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("3c138078-56b6-4b80-bcd4-beeb542c69fe"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b8adcbdf-d70b-45a1-bfe6-b5c21ba405cc"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d21ed9a2-a924-4f85-9b4d-b939ecab3ba6"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f92640cd-4efe-4dad-91b0-2687ff03f0b7"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("3f602bb8-fe92-45f3-8572-100492c646f9"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("90c81cd0-8353-434b-b477-9842bf7f0dbb"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("8537f5d7-1dee-425e-8c41-9c90d1116af0"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("a4f21b93-b9b8-4662-a7b5-39223961b775"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("13df2e93-e0c0-4952-9bf7-0043492cd4f1"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("16baa191-1935-4b71-b723-e60a082d2944"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("39da82c3-624a-4bf2-9c9f-b7a3c89f0e47"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("3d4d6990-b9fd-4f17-9592-cedc08649523"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("786f1b23-a080-4a41-aa2c-a09061a6ab6f"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("fb10024d-404f-4bcd-851f-8ebac3b2c93d"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("03565f88-dd7c-4dad-a0ae-5e8df53580c6"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("3c027cf7-4240-4367-bbf6-9273fe06ee4f"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f9079244-c795-4a52-b514-f646bc06da13"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("af64323b-86e1-4b88-8372-aa4ea2177013"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("84575b2b-1958-4e61-857d-b122dd2d851f"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("1cd3a199-eebb-4d75-8d7b-74bf54171a24"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("c52b00c2-70c5-401a-8e18-37839e03372b"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("4ff91018-59df-4c07-8b26-1f44a6ef564d"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("20a05dd9-f21c-47bb-9dea-0bb2352b83e8"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("dfe57531-76e0-4096-a6b8-e8546ae99895"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("e5c4cde3-1e35-42cb-9a6f-05603c026c99"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b9d84a94-5bc7-40d1-858b-a66689d01d5e"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        });
                });

            modelBuilder.Entity("BMS.Models.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BorrowerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("LoanBookId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LoanDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BorrowerId");

                    b.HasIndex("LoanBookId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("BMS.Models.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Borrower")
                        .HasColumnType("char(36)");

                    b.Property<int>("LoanTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("BMS.Models.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxBooks")
                        .HasColumnType("int");

                    b.Property<int>("MaxDays")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "fbae1800-3f60-497c-b66a-723b83c06915",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "074a4e18-4fac-4cc6-9658-bd46ecbab6fc",
                            Email = "horaoen@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            MaxBooks = 0,
                            MaxDays = 0,
                            NormalizedEmail = "HORAOEN@GMAIL.COM",
                            NormalizedUserName = "HORAOEN",
                            PasswordHash = "AQAAAAEAACcQAAAAENQLU/plCP8JDTCUYFKT8ojQlkN/3E96dTOMdMgjzhxQv+tkIRhO9jtE7HnpRYEKPg==",
                            PhoneNumber = "15137667148",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6db73cb7-50d8-4d9d-abce-d50076103033",
                            TwoFactorEnabled = false,
                            UserName = "horaoen"
                        },
                        new
                        {
                            Id = "ede90e59-9ab5-44f1-a7f3-74ae3e23379e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "299b58ff-8688-4384-9fd6-e143d4e1c061",
                            Email = "bleso624@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            MaxBooks = 0,
                            MaxDays = 0,
                            NormalizedEmail = "BLESO624@GMAIL.COM",
                            NormalizedUserName = "BLESO",
                            PasswordHash = "AQAAAAEAACcQAAAAEEWgIl12qUjaUiJMvexxWqqj9mB9lIwKtYJW/xyLao5LQOrEZRfNgdNx3WZGa+SGWg==",
                            PhoneNumber = "15137667148",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2d51c663-db88-4eda-8300-37a96e2efa8d",
                            TwoFactorEnabled = false,
                            UserName = "bleso"
                        },
                        new
                        {
                            Id = "aab6762a-a10b-48b2-bd6c-14d7be4548eb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "df6a50fb-0778-4f2b-837e-ba821dcfc789",
                            Email = "2495644988@qq.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            MaxBooks = 0,
                            MaxDays = 0,
                            NormalizedEmail = "2495644988@qq.com",
                            NormalizedUserName = "FHR",
                            PasswordHash = "AQAAAAEAACcQAAAAENiEE9uUNd/PHYrX+7DSK8MbLeLHI/EhFDeF7SXFbU/G/WuyAzKNO2FKlDpWJZhPwA==",
                            PhoneNumber = "15137667148",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1d8a312e-8e52-4e2c-b951-ff16862d5a47",
                            TwoFactorEnabled = false,
                            UserName = "fhr"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "5d5fcf5e-1619-4a58-bef7-ecd31fd9a38e",
                            ConcurrencyStamp = "eb14fbfa-823f-4687-8a92-9665573bd1d6",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "d2c594b2-3a84-4d28-9639-44549de6d704",
                            ConcurrencyStamp = "461aec14-3637-46c9-bd21-2c4b2a5adb03",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "e1badac2-52ef-46b6-978c-de38ca1490c9",
                            ConcurrencyStamp = "681dbdfd-7e32-48f5-be6a-009266384216",
                            Name = "Borrower",
                            NormalizedName = "BORROWER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "fbae1800-3f60-497c-b66a-723b83c06915",
                            RoleId = "5d5fcf5e-1619-4a58-bef7-ecd31fd9a38e"
                        },
                        new
                        {
                            UserId = "ede90e59-9ab5-44f1-a7f3-74ae3e23379e",
                            RoleId = "d2c594b2-3a84-4d28-9639-44549de6d704"
                        },
                        new
                        {
                            UserId = "aab6762a-a10b-48b2-bd6c-14d7be4548eb",
                            RoleId = "e1badac2-52ef-46b6-978c-de38ca1490c9"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BMS.Models.Entities.BookTitle", b =>
                {
                    b.HasOne("BMS.Models.Entities.User", null)
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("BMS.Models.Entities.BookTitleItem", b =>
                {
                    b.HasOne("BMS.Models.Entities.BookTitle", "BookTitle")
                        .WithMany("BookItems")
                        .HasForeignKey("BookTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookTitle");
                });

            modelBuilder.Entity("BMS.Models.Entities.Loan", b =>
                {
                    b.HasOne("BMS.Models.Entities.User", "Borrower")
                        .WithMany()
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BMS.Models.Entities.BookTitleItem", "LoanBook")
                        .WithMany()
                        .HasForeignKey("LoanBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Borrower");

                    b.Navigation("LoanBook");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BMS.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BMS.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BMS.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BMS.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BMS.Models.Entities.BookTitle", b =>
                {
                    b.Navigation("BookItems");
                });

            modelBuilder.Entity("BMS.Models.Entities.User", b =>
                {
                    b.Navigation("BorrowedBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
