// <auto-generated />
using System;
using BMS.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BMS.Models.Entities.BookTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("BorrowedNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Revations")
                        .HasColumnType("int");

                    b.Property<int>("TotalNumber")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BookTitles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            Author = "Ddrew Neil",
                            BorrowedNumber = 0,
                            Name = "Vim实用技巧",
                            Revations = 0,
                            TotalNumber = 20
                        },
                        new
                        {
                            Id = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            Author = "Eric Evans",
                            BorrowedNumber = 0,
                            Name = "领域驱动设计",
                            Revations = 0,
                            TotalNumber = 19
                        },
                        new
                        {
                            Id = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            Author = "张嘉佳",
                            BorrowedNumber = 0,
                            Name = "云边有个小卖铺",
                            Revations = 0,
                            TotalNumber = 90
                        },
                        new
                        {
                            Id = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            Author = "吴建",
                            BorrowedNumber = 0,
                            Name = "UML基础与Rose建模案例",
                            Revations = 0,
                            TotalNumber = 30
                        });
                });

            modelBuilder.Entity("BMS.Models.Entities.BookTitleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BookTitleId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsBorrowed")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("BookTitleId");

                    b.ToTable("BookTitleItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7238ef0f-7f5c-40f6-a4de-706c4e2ce8cf"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("a795a22e-665b-40be-9e80-ccb9fe67af62"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b3db57f0-42b5-4d18-871e-8dc2d6efeeb5"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("001a5972-c8da-4666-9b54-2b428b42146a"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("fe970fe0-2f3b-4f3f-afb2-68e9eb50aae6"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("3790726f-eff5-48ea-8eb8-c88a3c27f478"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("768a448d-65c1-480f-bd9d-389886e7bbc1"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("13d55f40-6ced-42f1-8716-b96fd8e253f7"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("06182634-6792-4295-9c56-5dffbaf0e845"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("5fc9c407-3584-4903-80fa-aaa185a04022"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("eab8f06a-c26d-4761-a744-0f04a330ee37"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("e3fe9c2d-4bd0-439a-b321-1bca444e89f3"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("622c2929-f993-4dc3-b126-596f9e5f6efb"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("8640a41d-4f9b-428a-b1ef-fc7df8b6bf81"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ec76225f-78e5-463f-8de9-9059bc6b2d89"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("7e31088a-1475-4e20-a0e9-75043b749e1f"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("450b4695-fef7-4706-a5d0-58252aece194"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("1fb144e8-7efa-43bd-9879-e088331f34ca"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("1e7f8ecf-7ae4-4c29-babb-8fefa9b2bc7b"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("5d07ac20-9d38-47f7-8581-0b1b9a332e4f"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d65df3cd-e5f4-4ac9-9f3a-c46699d4979f"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("24fb71d0-42a0-4444-b8a6-5dda7bc823a3"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("1168a598-1826-433c-818c-d99db156817e"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("0e584395-00fb-4f68-a20c-ee0b72f9c4f3"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("7fa46cad-0e4c-4fc4-9b4d-7817d3e70493"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("48d60fbe-d281-434f-bfd5-aed4bf46ebdc"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("13f727ad-6ffe-428e-8575-8c1520ef8874"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("5e132ae3-4cb5-4dec-a3e2-e9c5e320fc1e"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d8ec5063-00d6-4439-9c36-a1b880415d27"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b0e41f6e-5ac5-4ff2-8569-24027ac1e9bd"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("16466750-ce0a-4a97-90aa-b4db7e6eacc6"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("27120084-8b9a-4176-a13c-13d085a787ba"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("09147369-409f-44d4-90cb-171acbd91d6b"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("1e59361d-ddef-483a-9c06-ce67e374e3f0"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("4507e10d-4d72-4bc6-8ff8-81aeec37b3ee"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("06d1ca7a-5fc2-483c-b8a0-2f8734f0f896"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9fa837f2-8d9c-4f1c-a4e2-8d2f04fd2e66"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("1674b930-ea41-4ede-a04d-1e1a5afb2596"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("5a020d7a-c943-4e13-8fba-aa8ac12450d6"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("dc7ba6b8-93d1-451c-a9e9-7e4f70e9f17d"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("cb50c2eb-8b75-471b-9e03-5e2e6dd3a50f"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9d0be0a7-d1c4-49ed-b418-d9c939f1bf44"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("c65d8e4c-37bb-4d1e-bd96-ab08ddac4c28"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("c5fe9c45-01a6-4bb5-b8cc-fbee2fb7dc53"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("623add20-8615-4f99-a295-0f002fbc68e9"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("a394eef0-a168-4df3-879c-f59c6a2bd592"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("5c1d6fe4-2148-4467-8456-35d1ea7c08dc"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("1da076af-9daf-4aca-9ced-86749549b792"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b724b504-9100-4b8c-8040-1d9554f02389"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("557e0666-fb50-4c54-abf6-20959ef38ff4"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ae4453fa-4f6a-4b8e-8a6d-bff8ad45e3c8"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9ffe885d-6570-48b6-b222-d0806a394b80"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("707b9ea0-e203-46bc-b8c1-08751cf4b41a"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("7fa24a9f-d48a-4619-b3f0-6a3f6ff3fd59"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9c124eff-87e4-46c7-8776-96f72782cc91"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("63099e81-9a2b-4478-b104-8b90918c49f4"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b0ed4a74-3695-4f0d-9594-126e005b9012"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("c8097709-e8b6-4a69-a12d-090b4e3579d2"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9666e684-2a13-4132-a146-4621f7040a01"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("226b4929-faef-44bc-ba03-49fd66eac236"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("415deee5-0aa9-43e6-bd6d-55282206504e"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("de54bab6-c490-4338-8882-88b63bf7fbac"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("60cd4bed-57b1-4b00-a4d5-564cf3b225e9"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("cd29ec31-49fd-4f1a-a594-1f65dfbfd230"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9662ac79-cce4-44cc-92c9-1a9aec971c00"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("e93a9e28-6f2c-4bef-9432-b6a44f1c1691"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ed3a0e6e-8d63-45c1-a5e5-958b9f1e526a"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("0f2673fa-d76d-4c58-a67a-c6c6ec93ee0d"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("0c16ad5c-5ddc-4759-b681-2e6535a34082"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("81015edd-2bfd-43e1-828f-7d8ce432df5e"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("a20e9590-607c-42a6-9d24-e12e9e1cf7e6"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f5db26bf-b581-4d24-9cc2-05db3e020fd9"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("665d7122-cff5-42c4-a35e-aef4efd927ea"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("6f92621a-6007-44bf-9cee-3def7cf86479"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("10d7a17f-d5b3-4fbc-b721-2a142a447461"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("31f438b1-04f5-4bfd-bb9e-6fde8514384b"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("301622e9-d802-496a-9413-9a9e76682702"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b8184810-0372-46aa-87ec-21c2e8b56570"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("81c67b40-a80c-494e-be1e-f00c663c4608"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("26e25784-9837-41db-aa0e-7bc4321ccbca"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("0ef12683-3761-4204-ad77-784acf7f2b8a"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("2dfa6cec-3f74-418f-be7d-14bb6041f327"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b55ac11c-9b70-415d-837a-c107a624e06c"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d305293e-4fea-4938-aefd-4b57cb6e1de6"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("fcc73434-da60-4f5f-9bf6-e4320d373eae"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("2882d796-6b33-4b66-be9e-eaff9bfd29e5"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("702b4196-e175-4603-953f-a94047b10a6c"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("12e726f3-1c1a-4732-ad51-4fe0af0ba628"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("fcb052c5-e1b7-456a-97ea-c1201438d27f"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("2b7d2089-f868-4480-8013-890222f9fc9a"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("2fc58950-cb87-43f4-8924-0c3af4ccc44e"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("00dbadb4-8bbb-44a1-949f-f53deaba087c"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f2ee7e4c-d59b-4575-948b-2398ac8eb422"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("46cdf4e6-58ba-49c0-ab25-cb92a4448a80"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("415462e1-9276-49c5-8393-bc9664fe743e"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("21e1b6ed-0b5d-4b8d-8167-a8ab3678e485"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ba36732c-1060-4c81-a33c-4ec6fc850526"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("09b63498-05b2-4a53-9985-c227fd6716fe"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("1ca97727-20aa-4fb7-a677-8d5823273cad"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("baa7de4a-f2f3-405d-888d-af1ac1a6b623"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("e3fa800d-7819-4109-85ff-3a7a484c1ae6"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b6c0a506-10ef-48c3-aae8-d43fef4ccc74"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("2accd9c4-1f01-49a3-bad5-4bb4f06805c6"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("28b2b211-63cd-4c81-a28e-f5687a288c92"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("63ab4db8-359a-4b26-9fdb-9bb0cab7c4b1"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("dba7795c-65fe-4d05-89ef-eb3997afec64"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9bf2ef51-4edf-40de-9602-7ee2d9a1a158"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d33eabe3-1aa1-447c-a4f2-f94bff19bfc5"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("c418f232-0830-4f05-a8f3-81fd4556ac46"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("faf49759-92de-45d4-9e1f-9e053883191a"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f3230b22-c60e-42d6-b12c-5008634f36fc"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("e363e8d9-f106-4012-992d-9b2e0cccf39c"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9fd0171c-da02-4be8-985a-d1de69188b8d"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("7d9720c7-8964-4277-a505-cf714bceecfb"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("46bf3193-6b5e-4d85-84a7-b9bb0958013c"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("e715bbfe-e271-4df8-b56c-525afb15ae9b"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("98e3660b-31b0-4948-a785-caaacb8253a0"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("92d6a771-4a3c-4d15-8541-fdf38504ced3"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("679d9e71-ccb1-4bc4-89f8-8d93461eaa3f"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("00a99394-cd58-471c-9597-d61891623f25"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("261df779-d685-4508-ba64-6af300d68417"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("019c13df-fdd9-4a11-b4ad-1d8638683718"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("5a5f7a76-717c-413c-9f7d-2a73e9b1d296"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("621bee87-9f67-4c8d-bd48-c806a8205ca4"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f4b0ab12-0e54-4da5-b608-55a69fd6c208"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("74d62ec9-a143-4ee5-ada8-01ef616eb492"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("13f9d94a-b071-4424-96db-3b7de37ded1c"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("7fca5707-8e02-41bf-a30b-cd813b92a211"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9fe669eb-7b0d-460b-9859-65e8c19ee971"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f776c681-b906-4b82-8d6f-508d293f80dd"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("5f9434d2-eca3-4351-b78e-eaa1a6793717"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("65f457b6-f75e-4144-9d0e-5d20974cac9b"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("132f38c0-50a7-4780-a6dc-4e21432e2981"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("7c078d5b-0f4a-4453-a4c6-d52f583b88e4"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ac056cc0-9c48-4f89-a2ff-851b59ea9282"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("070d8cb2-9448-45c0-b62d-7a495c826ed7"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("33a54136-29f8-4595-8f7e-8265a22b3197"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("c1810f65-88b6-4421-82bc-b2349e28fe15"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("a9ac771b-ee79-4b94-9cbc-78acd2a55eab"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("1c16e157-5085-4ee2-b93a-65fb41f0052f"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("20668309-a338-41d3-b331-141394d6457f"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("3df14666-c57d-4426-b3be-0ae8b6e2e8e1"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("441699a4-a936-446d-8c79-7aff77bcaf54"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("7a4882d1-8253-4516-829d-a258ccc02838"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b7e14472-b7ba-44c3-9bb9-99f46a6077ae"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("92af1ba3-ba2f-4d91-9fc2-2d5dd87bee4d"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d29ff34a-4800-43fa-b116-5df58a8e9975"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("97d7b3a8-f802-4364-ab88-32ef7681781c"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("7c1ccaf4-de29-4fae-be11-a3411bfdb053"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("933336a3-97ff-4f6e-8ed6-a68984b2d24b"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ed5d7066-adbe-4afb-a71f-30344d9c40f0"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("a3cdb5d1-e864-4830-9587-515633ae4173"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("3e5df2f6-169a-4430-a7d9-e2264ec3c4ee"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("aad0ed39-727c-4440-b7cf-211eefc54950"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ca8989ef-671a-491c-b1a2-400fbe5897af"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("a555ec8a-b19f-4235-90b1-f186536ecef3"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("66280955-848e-44c5-a7b7-7c640327f01e"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("a984446c-d271-4665-874f-c52d855ab486"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("6497e07d-a7dc-4f1b-8b98-12b922ffcb32"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        });
                });

            modelBuilder.Entity("BMS.Models.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BorrowerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("LoanBookId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BorrowerId");

                    b.HasIndex("LoanBookId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("BMS.Models.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BookTitleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("BorrowerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LoanTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("BMS.Models.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Fine")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxBooks")
                        .HasColumnType("int");

                    b.Property<int>("MaxDays")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "51f79239-2133-417f-8a18-f8eae4701c3c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d1bcf478-d7eb-41ec-ac7a-1a63af3d7e44",
                            Email = "horaoen@gmail.com",
                            EmailConfirmed = false,
                            Fine = 0,
                            LockoutEnabled = false,
                            MaxBooks = 0,
                            MaxDays = 0,
                            NormalizedEmail = "HORAOEN@GMAIL.COM",
                            NormalizedUserName = "HORAOEN",
                            PasswordHash = "AQAAAAEAACcQAAAAEHT9zrjcVXSzwPnkKAeZ/EK6mDoC2DMbZ93/51e06GpcpK4LomuRr1a5b+ADeLU/Eg==",
                            PhoneNumber = "15137667148",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f642cd69-fb76-4d8d-990c-b312e313a660",
                            TwoFactorEnabled = false,
                            UserName = "horaoen"
                        },
                        new
                        {
                            Id = "273738c7-dd44-4148-8a1b-3d7479ffb95f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9f4d85b5-0b76-4c78-a4cb-94631c11b4d6",
                            Email = "bleso624@gmail.com",
                            EmailConfirmed = false,
                            Fine = 0,
                            LockoutEnabled = false,
                            MaxBooks = 0,
                            MaxDays = 0,
                            NormalizedEmail = "BLESO624@GMAIL.COM",
                            NormalizedUserName = "BLESO",
                            PasswordHash = "AQAAAAEAACcQAAAAEO4lHFFjj6AYs2OpVGCseeozeHTRSTiwon9UyL9ugzubimUFMmPE3/4oTBKjo7yXEg==",
                            PhoneNumber = "15137667148",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ae22c1b4-0b88-492d-b8e8-7c0591e2b182",
                            TwoFactorEnabled = false,
                            UserName = "bleso"
                        },
                        new
                        {
                            Id = "76bd0f60-3629-4e4d-b29e-c9dc7d921e85",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1b18a6f0-a36a-483f-a1bb-bd7f281abf0b",
                            Email = "2495644988@qq.com",
                            EmailConfirmed = false,
                            Fine = 0,
                            LockoutEnabled = false,
                            MaxBooks = 0,
                            MaxDays = 0,
                            NormalizedEmail = "2495644988@qq.com",
                            NormalizedUserName = "FHR",
                            PasswordHash = "AQAAAAEAACcQAAAAEMGlObB1KLwAyaRt7etuvnSO+KVnsyFD+SXSna4qtcqRE61dN1IZtpIuEENQpcK3aA==",
                            PhoneNumber = "15137667148",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4a223f09-be5b-4fae-bd50-d19757cfe05c",
                            TwoFactorEnabled = false,
                            UserName = "fhr"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "27de48b4-3b36-451a-bf4e-d6bc8bb57edf",
                            ConcurrencyStamp = "36c6dde2-91b5-4e6f-9586-ddc742d66b1c",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "a0109e2e-639b-4afb-b857-f1cc4e943d5f",
                            ConcurrencyStamp = "43f34dfa-cdd2-494f-a804-bffbd6cff702",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "a0d2b60a-1826-49ab-afc9-aff07f66dcfd",
                            ConcurrencyStamp = "e02931e0-f8c5-4682-b6af-5a4e16be8b93",
                            Name = "Borrower",
                            NormalizedName = "BORROWER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "51f79239-2133-417f-8a18-f8eae4701c3c",
                            RoleId = "27de48b4-3b36-451a-bf4e-d6bc8bb57edf"
                        },
                        new
                        {
                            UserId = "273738c7-dd44-4148-8a1b-3d7479ffb95f",
                            RoleId = "a0109e2e-639b-4afb-b857-f1cc4e943d5f"
                        },
                        new
                        {
                            UserId = "76bd0f60-3629-4e4d-b29e-c9dc7d921e85",
                            RoleId = "a0d2b60a-1826-49ab-afc9-aff07f66dcfd"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BMS.Models.Entities.BookTitle", b =>
                {
                    b.HasOne("BMS.Models.Entities.User", null)
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("BMS.Models.Entities.BookTitleItem", b =>
                {
                    b.HasOne("BMS.Models.Entities.BookTitle", "BookTitle")
                        .WithMany("BookItems")
                        .HasForeignKey("BookTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookTitle");
                });

            modelBuilder.Entity("BMS.Models.Entities.Loan", b =>
                {
                    b.HasOne("BMS.Models.Entities.User", "Borrower")
                        .WithMany()
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BMS.Models.Entities.BookTitleItem", "LoanBook")
                        .WithMany()
                        .HasForeignKey("LoanBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Borrower");

                    b.Navigation("LoanBook");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BMS.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BMS.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BMS.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BMS.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BMS.Models.Entities.BookTitle", b =>
                {
                    b.Navigation("BookItems");
                });

            modelBuilder.Entity("BMS.Models.Entities.User", b =>
                {
                    b.Navigation("BorrowedBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
