// <auto-generated />
using System;
using BMS.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BMS.Models.Entities.BookTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("BorrowedNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Revations")
                        .HasColumnType("int");

                    b.Property<int>("TotalNumber")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BookTitles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            Author = "Ddrew Neil",
                            BorrowedNumber = 0,
                            Name = "Vim实用技巧",
                            Revations = 0,
                            TotalNumber = 20
                        },
                        new
                        {
                            Id = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            Author = "Eric Evans",
                            BorrowedNumber = 0,
                            Name = "领域驱动设计",
                            Revations = 0,
                            TotalNumber = 19
                        },
                        new
                        {
                            Id = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            Author = "张嘉佳",
                            BorrowedNumber = 0,
                            Name = "云边有个小卖铺",
                            Revations = 0,
                            TotalNumber = 90
                        },
                        new
                        {
                            Id = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            Author = "吴建",
                            BorrowedNumber = 0,
                            Name = "UML基础与Rose建模案例",
                            Revations = 0,
                            TotalNumber = 30
                        });
                });

            modelBuilder.Entity("BMS.Models.Entities.BookTitleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BookTitleId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsBorrowed")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("BookTitleId");

                    b.ToTable("BookTitleItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67e5f820-42da-4a32-b8fb-5ee145af69e3"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("a910ca24-68c5-43c9-a2bd-d834b5dac350"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("8b0ec359-3eab-4456-9817-dea7be321782"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("a08b1d33-c939-4600-9129-a4198c996d4f"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b20a4e6e-a320-4f05-b03d-5ab3bea0be48"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("4f699fab-0a5e-428c-98c4-939368ae5568"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9c369052-9a65-497b-b5b0-0b1fccc32bd2"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("feaf1464-b4b7-4eda-95c4-d37fc06e5ee9"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("7f565129-21fb-43f9-b991-c50b2dad50c8"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("238ec501-50db-48d2-9d54-2945785f34e8"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("6f70e8ac-b0e9-419c-9e33-6cae093e142f"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("7c06deba-fdb7-4b94-b577-8e90704cf7b6"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d0aa3a29-cec7-4b23-afc5-0a745b0fc8df"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("81d7fcff-8555-460f-ab9b-8e4256c6bb29"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("15636b86-66ab-4ddb-9220-6d3b7394b5a3"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("376db46d-121e-4338-95ad-6faeb5294f4a"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f47c677d-fc68-4a60-9faa-0387605fc347"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("265402b1-a551-4b00-a2b9-37357fb4e0d1"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("c77f2b00-a39f-456b-84f8-ea6804565732"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ccc5a135-aaa8-4197-bd66-32665c7b9ee8"),
                            BookTitleId = new Guid("3ea3fa38-6409-2e3e-04f5-c0cc287c5c96"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d557cd34-428a-4bf6-b245-16ec1550ddc3"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("c4331ed4-cd89-43d2-995c-c86d31d2ae98"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("fea52fe2-eeef-4654-b2af-6d328eac0924"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("e1700c78-ab6d-4049-bcc6-02b0e7fcf332"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f61d972c-b062-41c6-8ea1-8f904bca8569"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("6f1a7e72-5707-41d3-8460-681f53387911"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("65caedcc-cf67-4bf3-a3e6-6af7be8a3be9"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ce3f49a2-a02b-409a-85ee-cbe7d9dc0a61"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b8ab77b2-f6cd-48fe-aee0-09620f8846c8"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ff06c24d-74d1-4bb6-b94d-3776b53a7804"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b5887e66-0ded-479a-a9dd-0e24bcb24408"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("c80046e0-db83-47bb-be06-744daf360a17"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("bcd5b47d-5c63-47cb-88f6-11986ea8634b"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("231c7373-6df2-47c1-a2c2-93103a97200f"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d46dbe4a-b0fb-4d4f-89eb-2cd9c26edae2"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("a5d4f9c2-42c9-4bd2-b6e7-725076b01031"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("bc8f780f-f448-4f58-a960-bdaa69dabd7b"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("89a78262-b0c7-45d6-8481-d227a96503db"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("19311cce-ee8a-4446-af7e-e39bc8a6950c"),
                            BookTitleId = new Guid("1abc27d5-73da-9a8c-ab95-5d7aa8a35f1e"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("5f227aef-6592-4507-b359-e45337f55ea1"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("8f8c6965-3d9c-4128-9255-795b34080e51"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("17163cd8-2663-4fb1-8a81-582ec0784197"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("53907f41-b650-4786-ba04-b08b4546dadd"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("cd8df9a7-fa1d-4d71-9ff7-b0871e74176c"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("0d67a4c2-6f07-42ff-aedb-b81f4c2a9af2"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b45811ed-7d1c-4fd1-9a74-60adb9a2204b"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("25097439-fd4e-4106-8ef5-d17d2c0bac85"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("0c9e9eff-9d5d-402c-96d7-6465b4335f86"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("c2bddb41-c6c0-4b34-b952-21d9a6c369d3"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("efc090f1-524b-444d-a78d-c69f953703df"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("22ed77cd-0bb9-4afc-8f7a-d57eeaebd39a"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ffe6fe1b-42ea-4ffb-9939-3ca8719e77d2"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("582adbca-8e6b-4fc3-a139-4ab65486413a"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("2a3183d8-e4e4-4c1d-9f7b-9baffa413c57"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d03c86aa-483f-4f81-a74f-b3542734f0ef"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ca0cfa65-595d-4441-9a64-50be17faad4c"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("7d0a30b3-5396-4b2b-aeb9-b86348af28e5"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("6738396a-4538-4f81-b317-5befaa1b88b1"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("1f4808fb-c695-42d5-abe1-0fe3d531f703"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("8c3f30c7-7be1-4408-ad69-baee47b4966f"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f2d35958-b848-4d3c-96b8-ff7ad00df2fd"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f0d56ae4-6b62-4129-a2ac-b1547d6e4322"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("781732c9-3a52-4b8a-818c-19f2d1275606"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("a8505385-8535-46a1-a243-5ff918ef9466"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("02a4af38-4a1f-41cb-ac46-e3518bb267e6"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("25b999ca-3540-485f-b5fb-e9dd5bea31ca"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f609f59f-4436-4894-8d25-1a30e504ec67"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("45e65cf5-404d-4754-aca0-2c9776ca33db"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("6fe57935-1758-42e6-b018-84081b94b71c"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("a750fa6d-cd85-434c-8e7f-d546fcc01563"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("efd54a0d-91a7-4951-96c9-eaa23b1667c9"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("8976593a-4ce0-473e-8ec8-f8dfe0326878"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("4256ab78-89d7-443a-a0d4-4859a608f8b7"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b8aea0ba-c8ba-4203-96cd-72ac860227fd"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("53132239-7902-4d35-a607-c04eea28b956"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("6c773f6b-9377-421b-9af2-26647ea041f0"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("8fdeb8df-8198-4acc-bf09-a7dabc9c4b76"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("81695e2d-091e-439f-97af-5b5b54329897"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9093b988-f111-48e9-9258-847ffbb91f83"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("da296b07-350a-498b-aaac-03f95e1186b0"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("c52cc687-8757-4d1a-9c12-eadd83dc4096"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("929efd16-6ec0-44ec-b107-2ba352a5bffa"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("047358b5-0887-4b46-85d5-c5cf8fd2722d"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("660f935d-75fe-4028-9e1b-df729fc65c2a"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("408ba744-f65b-4c4c-b892-0f5f11d49cfa"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("ee82a104-c610-4c54-bb81-04781bf60417"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("7e4fd7ab-5397-4ef3-ba3e-ec2c7278e76a"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("4fef7c01-b7c6-4acf-a1c8-d2de8d02123e"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("fc5d3997-0b18-4d32-84e5-ced911a2eeec"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("c495de40-89ae-4f69-b261-06294a71958a"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("3fdd5a46-e2cf-410b-9571-21a9eccb6320"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("610017bb-45f7-41a3-9def-9f0de96b325b"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("1db15fa0-c681-4267-a318-de4fc0816608"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9a00bd12-dc8e-424c-a151-722e496b428d"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("13711f07-d1c7-4caa-b3d0-d41fa996e647"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("a5adb271-cec1-438a-9cce-6e10349764d7"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("c9591b58-3a23-407d-ac5d-9027ec938193"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9732b646-75c4-4c58-8375-8fc8bcda627f"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("335e75d9-673e-4d5c-9cb5-a96efdeb26b7"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("60ecba86-f3a7-41af-9989-fa1f2f27ae86"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b00f191d-364a-435f-a3b6-c57d4bc3d876"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("66c9d535-3c4d-48a3-a5dd-9f8c80a8b811"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("4fef59b5-1945-4e85-9a8f-60db4ebfd489"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("42698ad0-707f-4d94-8bdd-73eacab4ef62"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("15bcc96d-d463-47b4-a285-8b9b12c559a8"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("3a21814a-a8a5-459d-977f-2694fa26c665"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("3289ca7f-70e7-4a64-8d84-23d22cea2150"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("4596b263-7217-4723-b6e6-db513a3f87ef"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("087c4282-d23c-4b9e-8ad2-8240712f542b"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("a19d0fba-b501-4cf0-81c0-101c04df6195"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("8b96c297-c99c-4a18-be8b-04c0fd035ae3"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("6aa96723-a806-4433-9116-293d3e9684d5"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("275ad9ab-6fe0-4375-8ddd-bfc8af742d6e"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("7ed8e4f7-d15f-41ec-851b-7f4594a82f2b"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("3490a173-052d-4a81-b05c-90f0580dd697"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("bd5dc722-9584-48ad-8780-d14b53798237"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d328b12a-a71a-4180-8d31-21be21b83e54"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("2fbc6a96-388d-46fe-a12b-a57cf550df24"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("5d3e00b0-50b9-4a40-9ac4-49a7e0c3e94d"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9ea97a56-e852-427e-983b-8fdae08590f6"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("966b1abd-5f89-4052-bd67-e9e5c6d3783c"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9ed4abcb-e58a-418b-b4e4-1686bad9c760"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("5b732643-13f9-43e5-9882-b60d609224e6"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f4b43402-1b95-41ae-9c8a-b26730bce001"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("3d6f1feb-d182-4c5f-8d0c-adf0462011a5"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("2d369224-c84a-41f7-b15e-f87364b5a45f"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("a237d96d-b43c-4b47-9caa-6db4ca3afe61"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("1b4209a9-9a12-4668-8cff-21387cc1e52b"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("225ba62e-58f2-4be8-b8ea-bf9d55b89e03"),
                            BookTitleId = new Guid("cbee1496-fc25-0d42-98cb-827cf70a69d1"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("95254c1a-5721-4bae-a250-8d985adb52e3"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("33445dc9-c60b-4cd6-aa78-0380a9711447"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("3f33ac99-c72d-4a77-a6c3-6fa13ee716b6"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("5238ff9b-31b5-4cbb-a9e6-54fd361993d3"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b597c472-bbd4-4bd3-8568-ea3fe0ba09a3"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d7593825-8a8e-4469-8ce2-7673f3b3a577"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("159447c3-e597-48b6-8cd4-06464e68b1f0"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("6874031d-246e-49e4-931e-c24be78879c9"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d802e2e3-2c66-459d-82d7-ae2cf5625b6b"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("deec8f8b-8f49-4060-a7f6-f91ba7b7f0ee"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("f10a78a6-ae89-4629-8f18-0a4daac3774c"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("79870c37-c3d1-4974-b06d-4bfe1e393c64"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("4ff5a3d7-db4b-4502-aac6-3e5c7d6d2430"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("8cc9146b-1a54-4857-923e-ae9c9e3c258a"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("facdb0d4-d3c7-48c8-a992-8bc026bc12f2"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("6f0a4a4b-a9b6-4332-999f-24c22fade088"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("2732b3ac-6670-493f-a2f0-c2a27b5d91ce"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("82c094eb-da5b-4f5f-b9bf-2269fefe5ee7"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("594db9dc-236a-4b69-8871-7a845d624d66"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("1d03834c-acc3-45c5-82df-d494376852f2"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("18d79e54-93b5-4dee-9a41-a44d81621554"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("d6ab27e9-fc98-43f9-8f5e-0c53af6b6b5d"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("8e8a8d7a-e891-4024-a7ac-a9a88c79c63b"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("b5cb3902-73d5-4c1e-b80b-8fcf680dcc91"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("74457367-91cf-4118-ab48-54a61749d9dc"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("3b13ae07-d084-458f-9de3-6567de8c1cc0"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("2e3b1f12-3cf5-417e-ae5d-f1a07301e24e"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("5060309e-8df3-450e-8f70-dffed1f365e9"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("2144cad2-c792-4aae-b308-4a03ffc33dde"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        },
                        new
                        {
                            Id = new Guid("9fcd1892-1e65-4e78-9c77-ee56db3a8656"),
                            BookTitleId = new Guid("7abb6e0a-3b6f-c5a1-2be8-32cdc779a93f"),
                            IsBorrowed = false
                        });
                });

            modelBuilder.Entity("BMS.Models.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BorrowerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("LoanBookId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BorrowerId");

                    b.HasIndex("LoanBookId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("BMS.Models.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BookTitleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BorrowerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("LoanTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("BMS.Models.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxBooks")
                        .HasColumnType("int");

                    b.Property<int>("MaxDays")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0a30aab1-077f-4db3-bea8-b4785159ebb3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f9334524-62f0-408e-9a20-4983ca7a3656",
                            Email = "horaoen@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            MaxBooks = 0,
                            MaxDays = 0,
                            NormalizedEmail = "HORAOEN@GMAIL.COM",
                            NormalizedUserName = "HORAOEN",
                            PasswordHash = "AQAAAAEAACcQAAAAEBSfwL6znViCPNW0PvGKelCS+DnE7389mZngtNyQEAUIaiWDS/Fz6mTps+A0HOplyw==",
                            PhoneNumber = "15137667148",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4b2a7da7-2400-4dac-9a6b-ca3e5fcfd9f2",
                            TwoFactorEnabled = false,
                            UserName = "horaoen"
                        },
                        new
                        {
                            Id = "75fede75-ab67-4d26-ad93-dcb19ba50b77",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a3dc3e34-88c0-4a8f-a254-038421dea9ae",
                            Email = "bleso624@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            MaxBooks = 0,
                            MaxDays = 0,
                            NormalizedEmail = "BLESO624@GMAIL.COM",
                            NormalizedUserName = "BLESO",
                            PasswordHash = "AQAAAAEAACcQAAAAEHG/6Jn/VoMClKsfdWo+XTaVcmrJ5AFo/m4JsAsiG5+ZN1CNmSkZ690NSgw1YvPxWA==",
                            PhoneNumber = "15137667148",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "02913bbd-fe81-486a-b96a-1dc9b1ef673c",
                            TwoFactorEnabled = false,
                            UserName = "bleso"
                        },
                        new
                        {
                            Id = "808ae985-840d-4f55-a8bd-7bffc96bd483",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "209fadb5-c2a5-426e-b3f6-c9bd3d6bd1a5",
                            Email = "2495644988@qq.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            MaxBooks = 0,
                            MaxDays = 0,
                            NormalizedEmail = "2495644988@qq.com",
                            NormalizedUserName = "FHR",
                            PasswordHash = "AQAAAAEAACcQAAAAENZe3yU0Ls5TCUItexoIulbEpB456o/nixZiSXna8Urw5K+fDplfIpqu41WwDJDGTA==",
                            PhoneNumber = "15137667148",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "68cacd60-7025-43b2-99f4-cfa58b61a114",
                            TwoFactorEnabled = false,
                            UserName = "fhr"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7ac8f186-9f75-4ce0-8400-6d4d6016c497",
                            ConcurrencyStamp = "4b502fec-3484-4cb0-a60c-73b460b45496",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "d6849c17-1891-4bb0-9232-997275f850fe",
                            ConcurrencyStamp = "6f94fd6c-c97a-410b-8faa-023bb18dd186",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "5c997943-a9c9-43c0-92ff-1f793d537b1f",
                            ConcurrencyStamp = "f6cd2ef5-a44e-4fcb-9528-1ad7e6754113",
                            Name = "Borrower",
                            NormalizedName = "BORROWER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "0a30aab1-077f-4db3-bea8-b4785159ebb3",
                            RoleId = "7ac8f186-9f75-4ce0-8400-6d4d6016c497"
                        },
                        new
                        {
                            UserId = "75fede75-ab67-4d26-ad93-dcb19ba50b77",
                            RoleId = "d6849c17-1891-4bb0-9232-997275f850fe"
                        },
                        new
                        {
                            UserId = "808ae985-840d-4f55-a8bd-7bffc96bd483",
                            RoleId = "5c997943-a9c9-43c0-92ff-1f793d537b1f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BMS.Models.Entities.BookTitle", b =>
                {
                    b.HasOne("BMS.Models.Entities.User", null)
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("BMS.Models.Entities.BookTitleItem", b =>
                {
                    b.HasOne("BMS.Models.Entities.BookTitle", "BookTitle")
                        .WithMany("BookItems")
                        .HasForeignKey("BookTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookTitle");
                });

            modelBuilder.Entity("BMS.Models.Entities.Loan", b =>
                {
                    b.HasOne("BMS.Models.Entities.User", "Borrower")
                        .WithMany()
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BMS.Models.Entities.BookTitleItem", "LoanBook")
                        .WithMany()
                        .HasForeignKey("LoanBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Borrower");

                    b.Navigation("LoanBook");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BMS.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BMS.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BMS.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BMS.Models.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BMS.Models.Entities.BookTitle", b =>
                {
                    b.Navigation("BookItems");
                });

            modelBuilder.Entity("BMS.Models.Entities.User", b =>
                {
                    b.Navigation("BorrowedBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
