name: .NET

env: 
  IMAGE_NAME:  test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v2
      with: 
        tags: horaoen/app:latest 
        push: true
        context: ./BMS
    - name: deploy
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        key: ${{ secrets.HOST_SSHKEY }}
        script: |
          docker stop bms-container
          docker rm bms-container
          docker rmi horaoen/app:latest
          docker pull horaoen/app:latest
          docker run -d --name bms-container -p 8080:80 horaoen/app
          

